# SPDX-FileCopyrightText: 2022 Dominic Martinez <dom@dominicm.dev>
#
# SPDX-License-Identifier: CC0-1.0

image: guix
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - haunt
  - guile
  - guile-reader
environment:
  site: dominicm.dev
tasks:
  - package: |
      cd website
      haunt build
      cd site
      tar -cvz * .well-known > ../../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
