image: guix
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - haunt
  - guile
  - guile-reader
environment:
  site: dominicm.dev
tasks:
  - package: |
      cd website
      haunt build
      cd site
      tar -cvz * > ../../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
