# SPDX-FileCopyrightText: 2022 Dominic Martinez <dom@dominicm.dev>
#
# SPDX-License-Identifier: CC0-1.0

image: guix
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
environment:
  site: dominicm.dev
tasks:
  - check: |
      guix shell -m manifest.scm -- reuse lint
  - package: |
      cd website
      guix shell -m manifest.scm -- haunt build
      cd site
      tar -cvz * .well-known > ../../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
